services:
  postgres:
    image: postgres:latest
    container_name: secrets-db
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: docker.io/bitnami/redis:7.4
    container_name: secrets-redis
    environment:
      - REDIS_PASSWORD= $REDIS_PASSWORD
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secrets-main-app
    env_file:
      - path: ./.env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app/src

volumes:
  db-data:
  redis_data:
    driver: local