services:
  postgres:
    image: postgres:latest
    container_name: secrets-db
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data: